version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: Clepsidra11
      MYSQL_DATABASE: playerstatsapplication
      MYSQL_ROOT_HOST: "%"
      TZ: Europe/Bucharest
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3309:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/playerstatsapplication?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&connectionTimeZone=LOCAL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Clepsidra11
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      TZ: Europe/Bucharest
    ports:
      - "8001:8080"
    restart: unless-stopped

volumes:
  dbdata: {}
